---
# tasks file for jenkins on RHEL
- name: add jenkins key
  rpm_key:
    state: present
    key: "{{ jenkins_key_rpm }}"

- name: Add Jenkins Yum repository
  yum_repository:
    name: "{{ item.value.name }}"
    baseurl: "{{ item.value.url }}"
    description: "{{ item.value.description }}"
  loop: "{{ lookup('dict', repos) }}"

- name: Install Jenkins
  yum:
    name: "{{ item.value.name }}"
    state: present
  loop: "{{ lookup('dict', softwares) }}"

- name: "Starting jenkins"
  service:
      name: "jenkins"
      state: started
      enabled: yes